
server:
  port: ${PORT:8888}

# Spring config
spring:
  cloud:
    config:
      server:
        git:
         uri: https://github.com/negociosdanet/microservice-repo
info:
  component: Config server
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
    encoding: '@project.build.sourceEncoding@'
    java.version: '@java.version@'