
server:
  port: ${PORT:8888}

# Spring config
spring:
  boot:
    admin:
      client:
        enabled: true
        url: ${URL_SPRING_MONITORING}
  cloud:
    config:
      server:
        git:
         uri: https://github.com/negociosdanet/microservice-repo