apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: mariosergioas/config-server:latest
          ports:
            - containerPort: 8888
          env:
            - name: PORT
              value: '8888'
          imagePullPolicy: Always
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /actuator/health
              port: 8888